# Generated by Django 3.0.5 on 2020-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('task_desc', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('image', models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/')),
            ],
        ),
    ]
